Repository selsa-inube/inubekit-toggle, pull requests merged in 2024-03, with the labels that each got.

#4 Refactor to component to use new token structure and new version of icon
  package-lock.json
  package.json
  src/Switch/stories/Switch.stories.tsx
  src/Switch/stories/SwitchController.tsx
  src/Switch/styles.js
  src/Toggle/index.tsx
  src/Toggle/props.ts
  src/Toggle/stories/Toggle.stories.tsx
  src/Toggle/stories/ToggleController.tsx
  src/Toggle/styles.js
  src/index.ts
  vite.config.ts
Labels: minor

#5 Implement try..catch in props of type function
  package.json
  src/Toggle/index.tsx
  src/Toggle/stories/Toggle.stories.tsx
Labels: minor

#6 Publish new version 1.1.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#7 Update inubekit/toggle to storybook v8
  package-lock.json
  package.json
Labels: dependencies

#8 Adjust and export interfaces
  src/Toggle/index.tsx
  src/Toggle/props.ts
  src/index.ts
Labels: minor

#9 Publish new version 1.2.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/Toggle/index.tsx
Labels: documentation
