Repository selsa-inube/inubekit-toggle, pull requests merged in 2024-09, with the labels that each got.

#36 Update foundations dependency to latest version
  package.json
Labels: minor, dependencies

#37 Update icon dependency to latest version
  package.json
Labels: minor, dependencies

#38 Update stack dependency to latest version
  package.json
Labels: minor, dependencies

#39 Update foundations dependency to latest version
  package.json
Labels: minor, dependencies

#40 Update icon dependency to latest version
  package.json
Labels: minor, dependencies

#41 Update stack dependency to latest version
  package.json
Labels: minor, dependencies

#42 Update foundations dependency to latest version
  package.json
Labels: minor, dependencies

#43 Update icon dependency to latest version
  package.json
Labels: minor, dependencies

#44 Update stack dependency to latest version
  package.json
Labels: minor, dependencies

#45 Update icon dependency to latest version
  package.json
Labels: minor, dependencies

#46 Enhance `<Toggle/>` Component to Support Custom Content with children Prop
  src/Toggle/index.tsx
  src/Toggle/props.ts
  src/Toggle/stories/Toggle.stories.tsx
  src/Toggle/styles.js
Labels: enhancement, major

#47 refactor: toggle and icon structure and positioning
  src/Toggle/index.tsx
  src/Toggle/stories/Toggle.stories.tsx
  src/Toggle/stories/ToggleController.tsx
  src/Toggle/styles.js
Labels: minor

#48 Update icon dependency to latest version
  package.json
Labels: minor, dependencies

#49 Move toggle tokens from foundations to component
  src/Toggle/Tokens/tokens.ts
  src/Toggle/index.tsx
  src/Toggle/stories/Toggle.stories.tsx
  src/Toggle/styles.js
Labels: minor

#50 Update icon dependency to latest version
  package.json
Labels: minor, dependencies
